#!/usr/bin/env bash
# Create a script to install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

# Install and configure HAProxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

#edit config file
server_config=\
"
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
backend web-backend
	balance roundrobin
	server 152975-web-01 52.87.215.57:80 check
	server 152975-web-02 34.229.49.137:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
