#!/usr/bin/env bash
# This script displays numbers 1 to 100
# Displays "FizzBuzz" for multiples of 3 and 5
# Displays "Fizz" for multiples of 3
# Displays "Buzz" for multiples of 5

for ((i = 1; i <= 100; i++))
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
