#!/usr/bin/env bash
# This script displays "Best School" and on the 9th
#+ iteration display "Best School" and "Hi"

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
		then echo "Hi"
	fi
	((i++))
done
