#!/usr/bin/env bash
# This script displays numbers from 1 to 20, on the 4th iteration
#+ it displays "bad luck from China, on the 9th, bad luck from Japan
#+ and on the 17th, bad luck from Italy

i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo -e "$i\nbad luck from China"
			;;
		9)
			echo -e "$i\nbad luck from Japan"
			;;
		17)
			echo -e "$i\nbad luck from Italy"
			;;
		*)
			echo -e "$i"
	esac
	((i++))
done
