#!/usr/bin/env bash
# Configure your SSH client to avoid inputing password every time you connect to your server

cat ~/.ssh/school.pub | ssh ubuntu@52.87.215.57\
	"mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"
